---
# [WARNING]: Could not find aptitude. Using apt-get instead fix
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes
# - name: "Install required packages"
#   package:
#     name: "{{ zeek_debian_reqs }}"
#     state: present


# - name: "Add zeek repository"
#   apt_repository:
#     repo: deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.04/ / #working
#     state: present
#     filename: security:zeek
- name: "Add zeek repository"
  template:
      src: security.zeek.list.j2
      dest: /etc/apt/sources.list.d/security:zeek.list
      owner: root
      group: root
      mode: 0644
- name: "Add an Apt signing key, uses whichever key is at the URL"
  apt_key:
    url: https://download.opensuse.org/repositories/security:zeek/xUbuntu_19.04/Release.key
    state: present

# - name: "Install zeek"
#   package:
#     name: "{{ item }}"
#     state: present
#   with_items:
#       - zeek
- name: "Install zeek"
  apt:
    name: zeek
    update_cache: yes
- name: "Check for zeek"
  stat:
   path: '/opt/zeek/bin/zeek'
  register: zeekpath
- name: "Set Path for zeek"
  lineinfile: dest='/etc/profile' regexp='^#?\s*export PATH=/opt/zeek(.*)$' line='export PATH=/opt/zeek/bin:$PATH' state=present
  when: zeekpath.stat.exists
